--
-- PostgreSQL database dump
--

\restrict DhS74LmTsYsCdcO1SCag7L5qEbGELJ0cId2wk1dgkv21zxwUAfp2eiOVG4vofx6

-- Dumped from database version 16.11 (Ubuntu 16.11-0ubuntu0.24.04.1)
-- Dumped by pg_dump version 16.11 (Ubuntu 16.11-0ubuntu0.24.04.1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: touch_user_last_update(); Type: FUNCTION; Schema: public; Owner: advance
--

CREATE FUNCTION public.touch_user_last_update() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
BEGIN
    UPDATE users
    SET last_update = NOW()
    WHERE user_id = NEW.user_id;

    RETURN NEW;
END;
$$;


ALTER FUNCTION public.touch_user_last_update() OWNER TO advance;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: beatmaps; Type: TABLE; Schema: public; Owner: advance
--

CREATE TABLE public.beatmaps (
    id integer NOT NULL,
    beatmap_id integer NOT NULL,
    beatmapset_id integer DEFAULT 0 NOT NULL,
    title character varying(255) DEFAULT ''::character varying NOT NULL,
    artist character varying(255) DEFAULT ''::character varying NOT NULL,
    creator character varying(255) DEFAULT ''::character varying NOT NULL,
    creator_id integer DEFAULT 0 NOT NULL,
    version character varying(255) DEFAULT ''::character varying NOT NULL,
    length integer DEFAULT 0 NOT NULL,
    ranked integer NOT NULL,
    last_update timestamp with time zone DEFAULT now() NOT NULL,
    added timestamp with time zone DEFAULT now() NOT NULL
);


ALTER TABLE public.beatmaps OWNER TO advance;

--
-- Name: beatmaps_id_seq; Type: SEQUENCE; Schema: public; Owner: advance
--

ALTER TABLE public.beatmaps ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.beatmaps_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: scores; Type: TABLE; Schema: public; Owner: advance
--

CREATE TABLE public.scores (
    id integer NOT NULL,
    user_id integer NOT NULL,
    beatmap integer,
    score_id bigint,
    score integer,
    accuracy real NOT NULL,
    max_combo integer,
    count_50 integer,
    count_100 integer,
    count_300 integer,
    count_miss integer,
    fc boolean NOT NULL,
    mods text[],
    "time" timestamp with time zone,
    rank character varying(3),
    passed boolean NOT NULL,
    pp real DEFAULT 0,
    mode smallint NOT NULL,
    added timestamp with time zone DEFAULT now()
);


ALTER TABLE public.scores OWNER TO advance;

--
-- Name: scores_id_seq; Type: SEQUENCE; Schema: public; Owner: advance
--

ALTER TABLE public.scores ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.scores_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: stats; Type: TABLE; Schema: public; Owner: advance
--

CREATE TABLE public.stats (
    id integer NOT NULL,
    user_id integer NOT NULL,
    global integer DEFAULT 999999999,
    country integer DEFAULT 999999999,
    pp real DEFAULT 0,
    accuracy real NOT NULL,
    playcount integer NOT NULL,
    playtime integer NOT NULL,
    score bigint NOT NULL,
    hits integer NOT NULL,
    level integer NOT NULL,
    progress integer NOT NULL,
    mode smallint NOT NULL,
    replays_watched integer DEFAULT 0 NOT NULL,
    day date DEFAULT CURRENT_DATE NOT NULL
);


ALTER TABLE public.stats OWNER TO advance;

--
-- Name: stats_base; Type: TABLE; Schema: public; Owner: advance
--

CREATE TABLE public.stats_base (
    id integer NOT NULL,
    user_id integer NOT NULL,
    badges integer DEFAULT 0 NOT NULL,
    banners integer DEFAULT 0 NOT NULL,
    followers integer DEFAULT 0 NOT NULL,
    achievements integer DEFAULT 0 NOT NULL,
    day date DEFAULT CURRENT_DATE NOT NULL
);


ALTER TABLE public.stats_base OWNER TO advance;

--
-- Name: stats_base_id_seq; Type: SEQUENCE; Schema: public; Owner: advance
--

ALTER TABLE public.stats_base ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.stats_base_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: stats_id_seq; Type: SEQUENCE; Schema: public; Owner: advance
--

ALTER TABLE public.stats ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.stats_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: advance
--

CREATE TABLE public.users (
    id integer NOT NULL,
    user_id integer NOT NULL,
    username character varying(255) DEFAULT ''::character varying NOT NULL,
    username_safe character varying(255) DEFAULT ''::character varying NOT NULL,
    country character(2) DEFAULT ''::character varying NOT NULL,
    restricted smallint DEFAULT 0 NOT NULL,
    discord character varying(20) DEFAULT '0'::character varying NOT NULL,
    last_update timestamp with time zone DEFAULT now() NOT NULL,
    added timestamp with time zone DEFAULT now() NOT NULL
);


ALTER TABLE public.users OWNER TO advance;

--
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: advance
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: beatmaps beatmaps_pkey; Type: CONSTRAINT; Schema: public; Owner: advance
--

ALTER TABLE ONLY public.beatmaps
    ADD CONSTRAINT beatmaps_pkey PRIMARY KEY (id);


--
-- Name: scores score_id_uni; Type: CONSTRAINT; Schema: public; Owner: advance
--

ALTER TABLE ONLY public.scores
    ADD CONSTRAINT score_id_uni UNIQUE (score_id);


--
-- Name: scores scores_go_pkey; Type: CONSTRAINT; Schema: public; Owner: advance
--

ALTER TABLE ONLY public.scores
    ADD CONSTRAINT scores_go_pkey PRIMARY KEY (id);


--
-- Name: stats_base stats_base_pkey; Type: CONSTRAINT; Schema: public; Owner: advance
--

ALTER TABLE ONLY public.stats_base
    ADD CONSTRAINT stats_base_pkey PRIMARY KEY (id);


--
-- Name: stats stats_go_pkey; Type: CONSTRAINT; Schema: public; Owner: advance
--

ALTER TABLE ONLY public.stats
    ADD CONSTRAINT stats_go_pkey PRIMARY KEY (id);


--
-- Name: users user_id_uni; Type: CONSTRAINT; Schema: public; Owner: advance
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT user_id_uni UNIQUE (user_id);


--
-- Name: users users_go_pkey; Type: CONSTRAINT; Schema: public; Owner: advance
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_go_pkey PRIMARY KEY (id);


--
-- Name: beatmaps_beatmap_id_idx; Type: INDEX; Schema: public; Owner: advance
--

CREATE UNIQUE INDEX beatmaps_beatmap_id_idx ON public.beatmaps USING btree (beatmap_id);


--
-- Name: idx_beatmaps_beatmap_id; Type: INDEX; Schema: public; Owner: advance
--

CREATE INDEX idx_beatmaps_beatmap_id ON public.beatmaps USING btree (beatmap_id);


--
-- Name: idx_stats_mode; Type: INDEX; Schema: public; Owner: advance
--

CREATE INDEX idx_stats_mode ON public.stats USING btree (mode);


--
-- Name: idx_stats_mode_country; Type: INDEX; Schema: public; Owner: advance
--

CREATE INDEX idx_stats_mode_country ON public.stats USING btree (mode, country);


--
-- Name: idx_stats_mode_global; Type: INDEX; Schema: public; Owner: advance
--

CREATE INDEX idx_stats_mode_global ON public.stats USING btree (mode, global);


--
-- Name: idx_stats_mode_pp; Type: INDEX; Schema: public; Owner: advance
--

CREATE INDEX idx_stats_mode_pp ON public.stats USING btree (mode, pp DESC);


--
-- Name: idx_stats_pp; Type: INDEX; Schema: public; Owner: advance
--

CREATE INDEX idx_stats_pp ON public.stats USING btree (pp DESC);


--
-- Name: idx_stats_user; Type: INDEX; Schema: public; Owner: advance
--

CREATE INDEX idx_stats_user ON public.stats USING btree (user_id);


--
-- Name: idx_stats_user_mode; Type: INDEX; Schema: public; Owner: advance
--

CREATE INDEX idx_stats_user_mode ON public.stats USING btree (user_id, mode);


--
-- Name: scores_go_user_id_mode_time_idx; Type: INDEX; Schema: public; Owner: advance
--

CREATE INDEX scores_go_user_id_mode_time_idx ON public.scores USING btree (user_id, mode, "time" DESC);


--
-- Name: stats_base_user_day_idx; Type: INDEX; Schema: public; Owner: advance
--

CREATE UNIQUE INDEX stats_base_user_day_idx ON public.stats_base USING btree (user_id, day);


--
-- Name: stats_user_mode_day_idx; Type: INDEX; Schema: public; Owner: advance
--

CREATE UNIQUE INDEX stats_user_mode_day_idx ON public.stats USING btree (user_id, mode, day);


--
-- Name: stats stats_touch_user; Type: TRIGGER; Schema: public; Owner: advance
--

CREATE TRIGGER stats_touch_user AFTER INSERT OR UPDATE ON public.stats FOR EACH ROW EXECUTE FUNCTION public.touch_user_last_update();


--
-- Name: SCHEMA public; Type: ACL; Schema: -; Owner: pg_database_owner
--

GRANT CREATE ON SCHEMA public TO advance;


--
-- PostgreSQL database dump complete
--

\unrestrict DhS74LmTsYsCdcO1SCag7L5qEbGELJ0cId2wk1dgkv21zxwUAfp2eiOVG4vofx6

